### PR TITLE
replaces git submodules with mbed submodules

### PR DESCRIPTION
**Pull request by geoffrey-vl**

### CODE REVIEW

**Comment by AGlass0fMilk** [comment]
Hey @geoffrey-vl,

thanks for the pull request!

I think it would simplify things if this repo used Mbed to manage dependencies as well.

Can you please make a branch that only has commit a459c85 ? 

You should be able to place things needed by the old version of Mbed (Span.h, etc) in a different part of your application. Therefore, I don't want to cause compatibility issues with the new version of Mbed by including redundant files.h

**Comment by geoffrey-vl** [comment]
I'll look for that.

But before I do that, I have som notes: I wouldn't make `uDisplay` a submodule. At least not entirely. Classes such as `ST7789.h` (and other drivers), and interfaces such as `UARTDisplayInterface.h` are also useful outside of `mbed-lvgl`, for say when some uses the unofficial implementations found in mbed such as GraphicalDisplay and TextDisplay. To support different graphical stacks, or maybe some game engine or uSDL framework (if it would ever exist) it better to have uDisplay as submodule in the application.

Also SSD1306 should be moved to uDisplay, am I correct?

**Comment by geoffrey-vl** [comment]
> Also SSD1306 should be moved to uDisplay, am I correct?

I've now noticed that the SSD1306 driver has already been moved to uDisplay, but it was never merged to master so that's why I've missed that.

**Comment by geoffrey-vl** [comment]
I've rewritten master to only include the commit you requested. My working code for SSD1309 is on local branches at this moment until I have a solid base to work upon.

**Pull request closed without merging**
